site_name: Basic MkDocs Example Project
theme:
  name: material
  highlightjs: true
# site_name: MkLorum
# site_url: https://example.com/
nav:
  - Home: index.md
  - About: file2.md

 

plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition